# Generated by Django 3.0.4 on 2020-03-19 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.ForeignKey(help_text='Select a language', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
        migrations.AddField(
            model_name='language',
            name='languageCode',
            field=models.CharField(default='en', help_text='Enter language code', max_length=2),
            preserve_default=False,
        ),
    ]
